//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cats
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    
        public virtual Owners Owner { get; set; }
    }
}
